USE [master]
GO

/****** Object:  Database [JiraService]    Script Date: 6/22/2021 6:20:33 PM ******/
CREATE DATABASE [JiraService]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'JiraService', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.TURINGSQLSERVER\MSSQL\DATA\JiraService.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'JiraService_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.TURINGSQLSERVER\MSSQL\DATA\JiraService_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [JiraService].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [JiraService] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [JiraService] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [JiraService] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [JiraService] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [JiraService] SET ARITHABORT OFF 
GO

ALTER DATABASE [JiraService] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [JiraService] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [JiraService] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [JiraService] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [JiraService] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [JiraService] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [JiraService] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [JiraService] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [JiraService] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [JiraService] SET  DISABLE_BROKER 
GO

ALTER DATABASE [JiraService] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [JiraService] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [JiraService] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [JiraService] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [JiraService] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [JiraService] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [JiraService] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [JiraService] SET RECOVERY FULL 
GO

ALTER DATABASE [JiraService] SET  MULTI_USER 
GO

ALTER DATABASE [JiraService] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [JiraService] SET DB_CHAINING OFF 
GO

ALTER DATABASE [JiraService] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [JiraService] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [JiraService] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [JiraService] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [JiraService] SET QUERY_STORE = OFF
GO

ALTER DATABASE [JiraService] SET  READ_WRITE 
GO


USE [JiraService]
GO

CREATE SCHEMA [db_board]
GO
CREATE SCHEMA [users]
GO